Ia81 4 lab5
iamillia/20102010 pull request #17
Opened 2019-03-17 17:20 UTC by NoThanksss

2019-03-17 18:36 UTC, KotyaraSingleCat commented on IA-81/4/laba5/laba5.1/src/calculating.java
> +            if(c1 == 0){
Вы, случайно, не забыли кинуть условие на а1?

2019-03-17 18:45 UTC, NoThanksss commented on IA-81/4/laba5/laba5.1/src/calculating.java
> +            if(c1 == 0){
В уравнении а1 может принимать любые значения

2019-03-17 18:52 UTC, NoThanksss commented on IA-81/4/laba5/laba5.1/src/calculating.java
> +            if(c1 == 0){
Есть пробитие

2019-03-18 06:44 UTC, alexivashina commented on IA-81/4/laba5/laba5.1/src/calculating.java
> +            if(c1 == 0){
++

2019-04-10 19:22 UTC, iamillia requested changes
Merge master branch and put your files to correct place, see README
Remove trash files

2019-04-14 17:41 UTC, closed without merging